import Head from "next/head";
import styled from "styled-components";
import Container from "../../components/Layout/container";
import Banner from "../../components/Banner";
import MainContainer from "../../containers/MainContainer";
import RangeSlider from "../../components/RangeSlider";
import { useState } from "react";
import Fitlers from "../../components/Filters";
import Product from "../../containers/Product";

const Main = styled.main``;

export default function Home() {
	const favFlagshipsGrid = { xs: 12, sm: 6, md: 4 };
	const trendingGrid = { xs: 12, sm: 6, md: 3 };
	const items = [{ id: 1 }, { id: 2 }, { id: 3 }];
	const onClick = () => {
		console.log("CLICK");
	};
	const [singleRange, setSingleRange] = useState(10);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Product />
		</>
	);
}
