import Head from "next/head";
import React, { useState } from "react";
import Container from "../../components/Layout/container";

import Fitlers from "../../components/Filters";
import MainContainer from "../../containers/MainContainer";
import ProductsContainer from "../../containers/ProductsContainer";
const Products = () => {
	const priceAboveGrid = { xs: 12, sm: 4, md: 3 };
	const items = [
		{ id: 1 },
		{ id: 2 },
		{ id: 3 },
		{ id: 4 },
		{ id: 5 },
		{ id: 6 },
		{ id: 7 },
		{ id: 8 },
		{ id: 9 },
		{ id: 10 },
		{ id: 11 },
		{ id: 12 },
		{ id: 13 },
		{ id: 14 },
		{ id: 15 },
		{ id: 16 },
	];

	const onClick = () => {
		console.log("CLICK");
	};
	return (
		<>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.svg" />
			</Head>

			<Container>
				<Fitlers />
				<MainContainer
					onClick={onClick}
					grid={priceAboveGrid}
					items={items}
					size="medium"
					border="top"
					cardBg="white"
					gapXs={5}
					gapSm={6}
				/>
			</Container>
			<ProductsContainer bg="light_gray" />
		</>
	);
};

export default Products;
