import Head from "next/head";
import styled from "styled-components";
import Container from "../components/Layout/container";
import Banner from "../components/Banner";
import MainContainer from "../containers/MainContainer";
import { useState } from "react";
import BlogsContainer from "../containers/BlogsContainer";
import Divider from "../components/Divider";
import Slider from "../containers/Slider";
const Main = styled.main``;

export default function Home() {
	const favFlagshipsGrid = { xs: 6, sm: 6, md: 4 };
	const trendingGrid = { xs: 6, sm: 6, md: 3 };
	const blogsGrid = { xs: 12, sm: 6, md: 4 };
	const priceAboveGrid = { xs: 6, sm: 4, md: 2 };
	const items = [
		{ id: 1 },
		{ id: 2 },
		{ id: 3 },
		{ id: 4 },
		{ id: 5 },
		{ id: 6 },
		{ id: 7 },
		{ id: 8 },
		{ id: 9 },
		{ id: 10 },
		{ id: 11 },
		{ id: 12 },
		{ id: 13 },
		{ id: 14 },
		{ id: 15 },
		{ id: 16 },
	];
	const onClick = () => {
		console.log("CLICK");
	};
	const [singleRange, setSingleRange] = useState(10);

	return (
		<>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.svg" />
			</Head>

			<Banner />
			{/* <Container>
        <Fitlers />
        <RangeSlider
          value={singleRange}
          max={100}
          onChange={(e) => {
            setSingleRange(e);
          }}
          symbol={''}
          size="md"
          hasLabels
        />
      </Container> */}
			<Container>
				<Slider title="Favorite Flagships" items={items?.slice(0, 3)}></Slider>
				<MainContainer
					className="hiddenXs"
					title="Favorite Flagships"
					onClick={onClick}
					grid={favFlagshipsGrid}
					items={items?.slice(0, 3)}
					gapSm={7}
					gapXs={4}
				/>
				<Divider />
				<MainContainer
					title="Trending"
					onClick={onClick}
					grid={trendingGrid}
					items={items?.slice(3, 11)}
					size="medium"
					cardBg="white"
					gapSm={5}
					gapXs={5}
				/>
				<Slider
					title="Top Rated"
					bg="yellow"
					hasBorder
					items={items?.slice(12, 16)}
				></Slider>
				<MainContainer
					className="hiddenXs"
					title="Top Rated"
					onClick={onClick}
					grid={trendingGrid}
					items={items?.slice(12, 16)}
					gapSm={5}
					gapXs={5}
					size="medium"
					border="bottom"
					cardBg="white"
					bg="yellow"
				/>
				<Divider className="hiddenXs" />
				<MainContainer
					title="Price Above Rs. 100,000"
					onClick={onClick}
					grid={priceAboveGrid}
					items={items?.slice(3, 9)}
					size="small"
					cardBg="white"
					gapSm={4}
					gapXs={5}
				/>
				<Slider
					title="People’s Choice"
					bg="purple"
					hasBorder
					items={items?.slice(12, 16)}
				></Slider>
				<MainContainer
					className="hiddenXs"
					title="People’s Choice"
					onClick={onClick}
					grid={trendingGrid}
					items={items?.slice(12, 16)}
					size="medium"
					border="bottom"
					cardBg="white"
					bg="purple"
					gapSm={5}
					gapXs={5}
				/>
				<Divider className="hiddenXs" />
				<MainContainer
					title="Price Below Rs. 50,000"
					onClick={onClick}
					grid={priceAboveGrid}
					items={items?.slice(3, 9)}
					size="small"
					cardBg="white"
					hiddenDown="xs"
					gapSm={4}
					gapXs={5}
				/>
				<Divider className="hiddenXs" />
				<MainContainer
					title="Price Below Rs. 20,000"
					onClick={onClick}
					grid={priceAboveGrid}
					items={items?.slice(3, 9)}
					size="small"
					cardBg="white"
					gapSm={4}
					gapXs={5}
				/>
				<Slider
					bg="light_green"
					title="Best Budget"
					hasBorder
					items={items?.slice(12, 16)}
				></Slider>
				<MainContainer
					className="hiddenXs"
					title="Best Budget"
					onClick={onClick}
					grid={trendingGrid}
					items={items?.slice(12, 16)}
					size="medium"
					border="bottom"
					cardBg="white"
					bg="light_green"
					gapSm={5}
					gapXs={5}
				/>
			</Container>
			<Slider
				bg="light_green"
				title="News & Reviews"
				items={items?.slice(0, 3)}
				type="blog"
				settings={{ slidesToShow: 1, centerMode: true, centerPadding: "24px" }}
			></Slider>
			<BlogsContainer
				items={items?.slice(0, 3)}
				grid={blogsGrid}
				bg="light_gray"
				className="mt-xs-0 mt-sm-20 hiddenXs"
			/>
		</>
	);
}
